### ISSUE TITLE
When running the multi tracker - getting error

### ISSUE THREAD

**Issue by ambakick** [inayatkh/tracking-python3#2]
MIL
Traceback (most recent call last):
  File "trackMultipleObjects.py", line 50, in <module>
    multipleTrackerOpenCV  = cv2.MultiTracker(trackerType)
SystemError: <class 'cv2.MultiTracker'> returned NULL without setting an erro

**Comment by inayatkh** [comment]
dear

compile correct version of opencv on your system before running my code

Dr. Inayatullah Khan
GM Tech
CESAT, Islamabad,Pakistan

Cell: +92-341-5000534

email: inayatkh@gmail.com

**Comment by zabir-nabil** [comment]
I'm trying with python3.6.8 and opencv==3.4.4
But, I'm getting this error:
[info] tracker selected is  0
Traceback (most recent call last):
  File "trackMultipleObjects.py", line 49, in <module>
    multipleTrackerOpenCV  = cv2.MultiTracker(trackerType)
SystemError: <class 'cv2.MultiTracker'> returned NULL without setting an error

![image](https://user-images.githubusercontent.com/10291263/76730922-7259fc80-6786-11ea-8bba-ad992a844321.png)

**Comment by faizan170** [comment]
@zabir-nabil It works with opencv 3.2 py 3.5
